name: Build and Bundle Analysis

on:
  pull_request:
    branches:
      - main # Main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # node -v

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.yarn
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --frozen-lockfile # install deps

      - name: Eslint update
        run: yarn lint:fix # eslint format

      - name: Run build
        run: |
          yarn build
          if [ $? -eq 0 ]; then
            echo "Build completed successfully"
          else
            echo "Build failed"
            exit 1
          fi

      - name: Analyze bundle size
        run: yarn analyze
        env:
          CI: true # it`s CI/CD runtime

      - name: Upload bundle report (optional)
        uses: actions/upload-artifact@v4
        with:
          name: bundle-report
          path: dist
